backend:
  name: github
  repo: abhishekSonawane97/foundation
  branch: main
  base_url: https://api.netlify.com

media_folder: "assets"
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/content.json"
        fields:
          - { label: "Hero Title", name: "hero_title", widget: "string" }
          - { label: "About Text", name: "about_text", widget: "text" }
          - { label: "About Sub Text", name: "about_sub_text", widget: "text" }
